openapi: 3.0.3
info:
    title: Todoタスク管理サービス
    description: HTTP service for todo management
    version: "1.0"
servers:
    - url: http://localhost:8088
paths:
    /add:
        post:
            tags:
                - todoservice
            summary: addTodoTask todoservice
            description: Todoタスクを追加する。
            operationId: todoservice#addTodoTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddTodoTaskRequestBody'
                        example:
                            asignee: Veritatis nihil ab voluptatum quia et est.
                            contents: Labore neque perspiciatis.
                            end_date: "1979-09-18"
                            label: Ut sapiente et.
                            start_date: "2003-09-14"
                            status: Tempore enim fugiat doloribus aut eos corrupti.
                            title: Maxime voluptas ut laudantium atque voluptatum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: boolean
                                example: true
                            example: true
    /todo/{id}:
        delete:
            tags:
                - todoservice
            summary: DeleteTodoTask todoservice
            description: 指定したTodoタスクを削除する。
            operationId: todoservice#DeleteTodoTask
            parameters:
                - name: id
                  in: path
                  description: Todo task id
                  required: true
                  schema:
                    type: integer
                    description: Todo task id
                    example: 4098841344247562326
                    format: int64
                  example: 2655990320106755604
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: boolean
                                example: false
                            example: false
        get:
            tags:
                - todoservice
            summary: GetTodoTask todoservice
            description: 指定したTodoタスクの詳細を取得する。
            operationId: todoservice#GetTodoTask
            parameters:
                - name: id
                  in: path
                  description: Todo task id
                  required: true
                  schema:
                    type: integer
                    description: Todo task id
                    example: 8810484951247058739
                    format: int64
                  example: 136946078425122329
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TodoTaskInfo'
                            example:
                                asignee: Id doloribus dignissimos sit voluptatibus et minima.
                                contents: Maxime quis sit debitis voluptate.
                                end_date: "2006-06-12"
                                id: 7521447378485825693
                                label: Autem amet distinctio cum quia ipsam quibusdam.
                                start_date: "2002-03-03"
                                status: Eum exercitationem ut sunt et.
                                title: Facilis voluptas est aut ut quas.
        put:
            tags:
                - todoservice
            summary: UpdateTodoTask todoservice
            description: 指定したTodoタスクを更新する。
            operationId: todoservice#UpdateTodoTask
            parameters:
                - name: id
                  in: path
                  description: Todo task id
                  required: true
                  schema:
                    type: integer
                    description: Todo task id
                    example: 7557921157924243086
                    format: int64
                  example: 6629694163848039858
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddTodoTaskRequestBody'
                        example:
                            asignee: Reprehenderit aut labore et saepe.
                            contents: Et atque recusandae esse.
                            end_date: "2002-05-25"
                            label: Ea et id.
                            start_date: "1985-02-15"
                            status: Eum atque repellendus.
                            title: Doloremque distinctio voluptates.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: boolean
                                example: true
                            example: false
    /todolist:
        get:
            tags:
                - todoservice
            summary: GetTodoTaskList todoservice
            description: Todoタスク一覧を取得する。
            operationId: todoservice#GetTodoTaskList
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/TodoTaskTitle'
                                description: Todo task list
                                example:
                                    - id: 4848195407315359599
                                      label: Explicabo dolorem.
                                      status: Molestiae sed ea commodi.
                                      title: Aperiam veniam aut.
                                    - id: 4848195407315359599
                                      label: Explicabo dolorem.
                                      status: Molestiae sed ea commodi.
                                      title: Aperiam veniam aut.
                                    - id: 4848195407315359599
                                      label: Explicabo dolorem.
                                      status: Molestiae sed ea commodi.
                                      title: Aperiam veniam aut.
                            example:
                                - id: 4848195407315359599
                                  label: Explicabo dolorem.
                                  status: Molestiae sed ea commodi.
                                  title: Aperiam veniam aut.
                                - id: 4848195407315359599
                                  label: Explicabo dolorem.
                                  status: Molestiae sed ea commodi.
                                  title: Aperiam veniam aut.
                                - id: 4848195407315359599
                                  label: Explicabo dolorem.
                                  status: Molestiae sed ea commodi.
                                  title: Aperiam veniam aut.
                                - id: 4848195407315359599
                                  label: Explicabo dolorem.
                                  status: Molestiae sed ea commodi.
                                  title: Aperiam veniam aut.
components:
    schemas:
        AddTodoTaskRequestBody:
            type: object
            properties:
                asignee:
                    type: string
                    description: タスクを割り当てられた人の名前
                    example: Et autem nam velit aut.
                contents:
                    type: string
                    description: Todoタスクの説明
                    example: Cupiditate distinctio at necessitatibus perferendis dolore maiores.
                end_date:
                    type: string
                    description: Todoタスクの終了予定日
                    example: "1978-02-19"
                    format: date
                label:
                    type: string
                    description: Todoタスクのラベル
                    example: Dolores recusandae voluptas dolore consequatur omnis minus.
                start_date:
                    type: string
                    description: Todoタスクの開始予定日
                    example: "1975-01-13"
                    format: date
                status:
                    type: string
                    description: Todoタスクの進捗状況
                    example: Corporis omnis quo cupiditate repellendus.
                title:
                    type: string
                    description: Todoタスクのタイトル
                    example: Tenetur minima.
            example:
                asignee: Voluptatem vitae.
                contents: Voluptas ut.
                end_date: "1970-12-08"
                label: Provident qui vel ut optio sit quo.
                start_date: "2011-12-15"
                status: Et ut voluptatem officia.
                title: Id eveniet laborum odit.
            required:
                - title
                - status
                - start_date
                - end_date
        TodoTaskInfo:
            type: object
            properties:
                asignee:
                    type: string
                    description: タスクを割り当てられた人の名前
                    example: Ratione iusto neque sunt iste nihil id.
                contents:
                    type: string
                    description: Todoタスクの説明
                    example: Sapiente sed quia accusamus et dolor.
                end_date:
                    type: string
                    description: Todoタスクの終了予定日
                    example: "1994-05-31"
                    format: date
                id:
                    type: integer
                    description: TodoタスクのユニークID
                    example: 3226082594794051886
                    format: int64
                label:
                    type: string
                    description: Todoタスクのラベル
                    example: Suscipit facilis perspiciatis corporis dolor.
                start_date:
                    type: string
                    description: Todoタスクの開始予定日
                    example: "1974-05-23"
                    format: date
                status:
                    type: string
                    description: Todoタスクの進捗状況
                    example: Ea ut id.
                title:
                    type: string
                    description: Todoタスクのタイトル
                    example: Qui debitis voluptas veritatis.
            description: Todo task
            example:
                asignee: Vitae ut libero aut alias totam et.
                contents: Et quod.
                end_date: "1996-12-21"
                id: 7623198298197173500
                label: Exercitationem aut voluptatem voluptatum.
                start_date: "1995-05-09"
                status: Aperiam blanditiis deleniti repellendus aut.
                title: Eos harum et.
            required:
                - id
                - title
                - status
        TodoTaskTitle:
            type: object
            properties:
                id:
                    type: integer
                    description: TodoタスクのユニークID
                    example: 1626908937817318796
                    format: int64
                label:
                    type: string
                    description: Todoタスクのラベル
                    example: Placeat numquam corporis.
                status:
                    type: string
                    description: Todoタスクの進捗状況
                    example: Ratione nihil eligendi esse et a.
                title:
                    type: string
                    description: Todoタスクのタイトル
                    example: Voluptas voluptas atque et perferendis.
            description: Todoタスクの情報
            example:
                id: 4183759292041169745
                label: Aliquam atque exercitationem temporibus.
                status: Eius soluta pariatur et ut.
                title: Enim sunt sit nostrum illum a.
            required:
                - id
                - title
                - status
tags:
    - name: todoservice
      description: Todoタスク管理サービス
